### ISSUE TITLE
Unable to highlight device explorer text

### ISSUE THREAD

**Issue by AlexSneedMiller** [3mcloud/azure-iot-platform-dotnet#194]
**Describe the bug**

When viewing Device Explorer, I cannot highlight text within the rows of the devices (e.g. Device name). I would be great if I could highlight the "Device name" so I can copy it and paste it elsewhere. If I click on the device, then the flyout menu shows up I am able to copy the Device name there.

**To Reproduce**
1. Go to device explorer
2. attempt to highlight the device name or any other attribute of the device
3. notice that you cannot highlight it

![image](https://user-images.githubusercontent.com/3960615/95510568-c410e100-097b-11eb-89a3-5c6cd8297e8f.png)

**Expected behavior**
highlight the text

**Screenshots**
Here's an example of highlighting the text in the flyout menu

![image](https://user-images.githubusercontent.com/3960615/95510637-ddb22880-097b-11eb-9831-9a14ba968376.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 85.0.4183.121 (Official Build) (64-bit)

[AB#22244](https://dev.azure.com/3M-Bluebird/150135ff-890c-41c0-8f52-1cfcd5f891df/_workitems/edit/22244)

**Comment by JonathanAsbury-ACS** [comment]
This functionality has been completed and merged here:  https://github.com/3mcloud/azure-iot-platform-dotnet/pull/195
It will be part of the next release deployed to you.
